### ISSUE TITLE
Night Guard AI

### ISSUE THREAD

**Issue by VoxAndrews** [VoxAndrews/Penquin-Thief#1]
**Bug Description**
The Night Guard AI is bugged as he does not move along the different NavMesh points and does not follow the player when in sight.

**Version Found**
Penguin Thief v0.1-alpha

**To Reproduce**
Steps to reproduce the behaviour:
1. Start the Game
2. Move Towards the Night Guard NPC
3. Notice that he is not moving/interacting with the player

**Expected behaviour**
The Night Guard should be moving along the NavMesh paths and should be chasing the player when in range.

**Desktop**
 - OS: Windows 10 (x86/x64)

**Comment by ZarKu1203** [comment]
Fixed the issue already, and pushed the fixed ai to origin.
